name: E2E Test for STAGING Environment

on:
  workflow_dispatch:

jobs:
  test:
    name: E2E Test
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Cypress run
        uses: cypress-io/github-action@v4
        with:
          record: true
          spec: cypress/e2e/criticalpath.cy.js
          config: baseUrl=https://staging.application.com/
        env:
          CYPRESS_PASSWORD: ${{ secrets.STAGING_PASSWORD }}
          CYPRESS_ENVIRONMENT: staging
